//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.11 at 11:51:27 AM BRST 
//


package com.b2wdigital.nfe.schema.v4v160b.epec.e110140_v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.b2wdigital.nfe.schema.v4v160b.epec.e110140_v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VST_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "vST");
    private final static QName _VICMS_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "vICMS");
    private final static QName _VerAplic_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "verAplic");
    private final static QName _TpNF_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "tpNF");
    private final static QName _UF_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "UF");
    private final static QName _VNF_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "vNF");
    private final static QName _DhEmi_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "dhEmi");
    private final static QName _IE_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "IE");
    private final static QName _DescEvento_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "descEvento");
    private final static QName _COrgaoAutor_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "cOrgaoAutor");
    private final static QName _TpAutor_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "tpAutor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.b2wdigital.nfe.schema.v4v160b.epec.e110140_v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DetEvento }
     * 
     */
    public DetEvento createDetEvento() {
        return new DetEvento();
    }

    /**
     * Create an instance of {@link DetEvento.Dest }
     * 
     */
    public DetEvento.Dest createDetEventoDest() {
        return new DetEvento.Dest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "vST")
    public JAXBElement<String> createVST(String value) {
        return new JAXBElement<String>(_VST_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "vICMS")
    public JAXBElement<String> createVICMS(String value) {
        return new JAXBElement<String>(_VICMS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "verAplic")
    public JAXBElement<String> createVerAplic(String value) {
        return new JAXBElement<String>(_VerAplic_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "tpNF")
    public JAXBElement<String> createTpNF(String value) {
        return new JAXBElement<String>(_TpNF_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TUf }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "UF")
    public JAXBElement<TUf> createUF(TUf value) {
        return new JAXBElement<TUf>(_UF_QNAME, TUf.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "vNF")
    public JAXBElement<String> createVNF(String value) {
        return new JAXBElement<String>(_VNF_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "dhEmi")
    public JAXBElement<String> createDhEmi(String value) {
        return new JAXBElement<String>(_DhEmi_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "IE")
    public JAXBElement<String> createIE(String value) {
        return new JAXBElement<String>(_IE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "descEvento")
    public JAXBElement<String> createDescEvento(String value) {
        return new JAXBElement<String>(_DescEvento_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "cOrgaoAutor")
    public JAXBElement<String> createCOrgaoAutor(String value) {
        return new JAXBElement<String>(_COrgaoAutor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "tpAutor")
    public JAXBElement<String> createTpAutor(String value) {
        return new JAXBElement<String>(_TpAutor_QNAME, String.class, null, value);
    }

}
