CREATE TABLE DOCUMENTO_RETORNO (
     DRET_ID_DOC_FISCAL INTEGER    
    ,DRET_TP_SERVICO    VARCHAR(100) 
    ,DRET_TP_EVENTO     INTEGER 
    ,DRET_ID_XML        INTEGER    
    ,DRET_URL           VARCHAR(2000)    
    ,DRET_USUARIO_REG   VARCHAR(100) 
    ,DRET_DATAHORA_REG  DATE          
    ,DRET_USUARIO       VARCHAR(100) 
    ,DRET_DATAHORA      DATE
);