CREATE TABLE DOCUMENTO_EVENTO (
     DOEV_ID_EVENTO      INTEGER    
    ,DOEV_ID_DOC_FISCAL  INTEGER    
    ,DOEV_ID_PONTO       VARCHAR(5) 
    ,DOEV_TP_SERVICO     VARCHAR(100)     
    ,DOEV_SITUACAO_AUTOR INTEGER    
    ,DOEV_ID_XML         INTEGER    
    ,DOEV_USUARIO        VARCHAR(100) 
    ,DOEV_DATAHORA       DATE
);