CREATE TABLE ESTADO (
     ESTA_ID_ESTADO INTEGER
    ,ESTA_ID_UF     VARCHAR(2)
    ,ESTA_NOME      VARCHAR(100)
    ,ESTA_COD_IBGE  INTEGER
    ,ESTA_USUARIO   VARCHAR(100)
    ,ESTA_DATAHORA  DATE
);